site_name: Django Typst Engine
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/a-musing-moose/django-typst-engine/
extra_javascript:
  - js/readthedocs.js
theme:
  name: "material"
  palette:
    primary: "green"
    accent: "green"
  icon:
    logo: material/book
  custom_dir: docs/overrides

markdown_extensions:
  - abbr
  - admonition
  - meta
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
